version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: andrewjameswormald/udaview:reverseproxy-latest
  backend_user:
    build:
      context: ../../backend-user
    image: andrewjameswormald/udaview:user-latest
  backend_feed:
    build:
      context: ../../backend-feed
    image: andrewjameswormald/udaview:feed-latest
  frontend:
    build:
      context: ../../frontend
    image: andrewjameswormald/udaview:frontend-latest
