version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: andrewjameswormald/viewagram:reverseproxy-latest
  backend_user:
    build:
      context: ../../backend-user
    image: andrewjameswormald/viewagram:user-latest
  backend_feed:
    build:
      context: ../../backend-feed
    image: andrewjameswormald/viewagram:feed-latest
  frontend:
    build:
      context: ../../frontend
    image: andrewjameswormald/viewagram:frontend-latest
