version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: andrewjameswormald/viewagramreverseproxy-latest
  backend_user:
    build:
      context: ../../backend-user
    image: andrewjameswormald/viewagramuser-latest
  backend_feed:
    build:
      context: ../../backend-feed
    image: andrewjameswormald/viewagramfeed-latest
  frontend:
    build:
      context: ../../frontend
    image: andrewjameswormald/viewagramfrontend-latest
